const VALID_STATUSES=["Aguardando resposta","Respondido no prazo","Aguardando resposta fora do prazo","Respondido fora do prazo"];
const INSIDE=new Set(["Aguardando resposta","Respondido no prazo"]);
const ANSWERED=new Set(["Respondido no prazo","Respondido fora do prazo"]);
const COLORS={green:"#22c55e",red:"#ef4444",blue:"#38bdf8",purple:"#a78bfa",orange:"#fb923c",yellow:"#facc15",grid:"#263852",text:"#94a3b8"};
let allData=[],charts={};
const $=id=>document.getElementById(id);
Chart.defaults.color=COLORS.text;Chart.defaults.borderColor=COLORS.grid;Chart.defaults.font.family="Inter, Segoe UI, sans-serif";

$("excelFile").addEventListener("change",importExcel);$("regionalFilter").addEventListener("change",applyFilters);$("gestorFilter").addEventListener("change",applyFilters);$("statusFilter").addEventListener("change",applyFilters);$("resetFilters").addEventListener("click",resetFilters);$("clearData").addEventListener("click",clearData);
restoreData();

function importExcel(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:"array",cellDates:true});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:"",raw:false});if(!rows.length)throw new Error("A planilha não possui registros.");const required=["id","titulo_denuncia","descricao_denuncia","data_de_abertura","resposta","data_de_resposta","regional","gestor_responsável","status_resposta"];const missing=required.filter(c=>!(c in rows[0]));if(missing.length)throw new Error("Colunas não encontradas: "+missing.join(", ")+".");const normalized=rows.map(normalizeRow);const invalid=normalized.filter(r=>!VALID_STATUSES.includes(r.status_resposta));if(invalid.length)throw new Error(`${invalid.length} registro(s) possuem status_resposta inválido. Valores aceitos: ${VALID_STATUSES.join("; ")}.`);allData=normalized;const meta={name:file.name,updated:new Date().toISOString()};localStorage.setItem("denuncias_dashboard",JSON.stringify(allData));localStorage.setItem("denuncias_meta",JSON.stringify(meta));setMeta(meta);populateFilters();applyFilters();showMessage(`${allData.length} registros importados com sucesso.`,"success")}catch(err){showMessage(err.message,"error")}};reader.readAsArrayBuffer(file);event.target.value=""}
function normalizeRow(r){return{...r,id:text(r.id),titulo_denuncia:text(r.titulo_denuncia),descricao_denuncia:text(r.descricao_denuncia),data_de_abertura:text(r.data_de_abertura),resposta:text(r.resposta),data_de_resposta:text(r.data_de_resposta),regional:text(r.regional)||"Não informado",gestor_responsável:text(r["gestor_responsável"]||r.gestor_responsavel)||"Não informado",status_resposta:text(r.status_resposta)}}
function text(v){return v==null?"":String(v).trim()}
function restoreData(){try{const saved=JSON.parse(localStorage.getItem("denuncias_dashboard")||"[]");const meta=JSON.parse(localStorage.getItem("denuncias_meta")||"null");if(saved.length){allData=saved;setMeta(meta);populateFilters();applyFilters()}}catch(e){localStorage.removeItem("denuncias_dashboard");localStorage.removeItem("denuncias_meta")}}
function setMeta(meta){if(!meta)return;$("fileName").textContent=meta.name||"Planilha carregada";$("lastUpdate").textContent="Última atualização: "+new Date(meta.updated).toLocaleString("pt-BR")}
function populateFilters(){fillSelect("regionalFilter",unique(allData.map(r=>r.regional)));fillSelect("gestorFilter",unique(allData.map(r=>r["gestor_responsável"])));fillSelect("statusFilter",VALID_STATUSES)}
function unique(values){return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"))}
function fillSelect(id,values){const s=$(id),first=s.options[0].outerHTML;s.innerHTML=first+values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join("")}
function resetFilters(){["regionalFilter","gestorFilter","statusFilter"].forEach(id=>$(id).value="");applyFilters()}
function applyFilters(){const regional=$("regionalFilter").value,gestor=$("gestorFilter").value,status=$("statusFilter").value;const data=allData.filter(r=>(!regional||r.regional===regional)&&(!gestor||r["gestor_responsável"]===gestor)&&(!status||r.status_resposta===status));render(data)}
function render(data){const total=data.length,inside=data.filter(r=>INSIDE.has(r.status_resposta)).length,outside=total-inside,answered=data.filter(r=>ANSWERED.has(r.status_resposta)).length;setText("total",total);setText("dentroPrazo",inside);setText("foraPrazo",outside);setText("respondidas",answered);setText("dentroPercent",`${percent(inside,total)}% do total`);setText("foraPercent",`${percent(outside,total)}% do total`);setText("respondidasPercent",`${percent(answered,total)}% do total`);setText("farolPercent",`${percent(inside,total)}%`);setText("recordCount",`${total} registro${total===1?"":"s"}`);const badge=$("farolBadge");badge.textContent=total?`${inside} dentro | ${outside} fora`:"Sem dados";badge.className="badge "+(total?(outside>inside?"bad":"good"):"");renderCharts(data,inside,outside,answered,total);renderTable(data)}
function renderCharts(data,inside,outside,answered,total){destroyCharts();charts.farol=new Chart($("farolChart"),{type:"doughnut",data:{labels:["Dentro do prazo","Fora do prazo"],datasets:[{data:[inside,outside],backgroundColor:[COLORS.green,COLORS.red],borderWidth:0,hoverOffset:5}]},options:{responsive:true,maintainAspectRatio:false,cutout:"72%",plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.label}: ${c.raw}`}}}}});const counts=VALID_STATUSES.map(s=>data.filter(r=>r.status_resposta===s).length);charts.status=new Chart($("statusChart"),{type:"bar",data:{labels:["Aguardando","Respondido no prazo","Aguardando fora","Respondido fora"],datasets:[{label:"Denúncias",data:counts,backgroundColor:[COLORS.green,COLORS.green,COLORS.red,COLORS.red],borderRadius:7,maxBarThickness:45}]},options:chartOptions(false)});const regions=countBy(data,"regional");charts.regional=new Chart($("regionalChart"),{type:"bar",data:{labels:Object.keys(regions),datasets:[{label:"Denúncias",data:Object.values(regions),backgroundColor:palette(Object.keys(regions).length),borderRadius:7,maxBarThickness:48}]},options:chartOptions(false)});charts.response=new Chart($("responseChart"),{type:"pie",data:{labels:["Respondidas","Aguardando resposta"],datasets:[{data:[answered,total-answered],backgroundColor:[COLORS.blue,COLORS.purple],borderColor:"#142238",borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{boxWidth:10,usePointStyle:true,padding:18}}}}})}
function chartOptions(horizontal){return{responsive:true,maintainAspectRatio:false,indexAxis:horizontal?"y":"x",plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{beginAtZero:true,grid:{color:COLORS.grid},ticks:{precision:0,font:{size:9}}}}}}
function countBy(data,key){return data.reduce((acc,r)=>{const v=r[key]||"Não informado";acc[v]=(acc[v]||0)+1;return acc},{})}
function palette(n){const p=[COLORS.blue,COLORS.purple,COLORS.orange,COLORS.yellow,"#14b8a6","#f472b6"];return Array.from({length:n},(_,i)=>p[i%p.length])}
function destroyCharts(){Object.values(charts).forEach(c=>c.destroy());charts={}}
function renderTable(data){const body=$("dataBody");if(!data.length){body.innerHTML='<tr><td colspan="7" class="empty">Nenhum registro encontrado para os filtros selecionados.</td></tr>';return}body.innerHTML=data.map(r=>{const within=INSIDE.has(r.status_resposta);return`<tr><td>${escapeHtml(r.id)}</td><td title="${escapeHtml(r.descricao_denuncia)}">${escapeHtml(r.titulo_denuncia)}</td><td>${escapeHtml(formatDate(r.data_de_abertura))}</td><td>${escapeHtml(formatDate(r.data_de_resposta)||"Não respondida")}</td><td>${escapeHtml(r.regional)}</td><td>${escapeHtml(r["gestor_responsável"])}</td><td><span class="status-pill ${within?"in":"out"}"><i class="dot ${within?"green":"red"}"></i>${escapeHtml(r.status_resposta)}</span></td></tr>`}).join("")}
function formatDate(v){if(!v)return"";const d=new Date(v);return isNaN(d)?v:d.toLocaleDateString("pt-BR")}
function percent(v,total){return total?Math.round(v/total*100):0}
function setText(id,v){$(id).textContent=v}
function showMessage(msg,type){const el=$("message");el.textContent=msg;el.className=`message show ${type}`;setTimeout(()=>el.className="message",6000)}
function clearData(){allData=[];localStorage.removeItem("denuncias_dashboard");localStorage.removeItem("denuncias_meta");$("fileName").textContent="Nenhuma planilha importada";$("lastUpdate").textContent="Última atualização: --";populateFilters();render([]);showMessage("Dados locais removidos.","success")}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}